name: bias-cpu
channels:
  - huggingface
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cpuonly=2.0
  - cryptography=36.0.0
  - dataclasses=0.8
  - ffmpeg=4.3
  - filelock=3.6.0
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - huggingface_hub=0.5.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1n
  - packaging=21.3
  - pillow=9.0.1
  - pip=21.2.2
  - protobuf=3.19.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.7.13
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - sacremoses=master
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tokenizers=0.10.3
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.63.0
  - transformers=4.11.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - datasets==2.0.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - entrypoints==0.4
    - fastjsonschema==2.15.3
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - importlib-resources==5.7.0
    - ipykernel==6.13.0
    - ipython==7.32.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - jsonschema==4.4.0
    - jupyter-client==7.2.2
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.2.1
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - notebook==6.4.10
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pyarrow==7.0.0
    - pygments==2.11.2
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyzmq==22.3.0
    - responses==0.18.0
    - send2trash==1.8.0
    - soupsieve==2.3.2
    - terminado==0.13.3
    - tinycss2==1.1.1
    - tornado==6.1
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - xxhash==3.0.0
    - yarl==1.7.2
